#!/bin/sh
d=""
[ -z "$SOURCE_DATE_EPOCH" ] || d=--date=@$SOURCE_DATE_EPOCH

FILES=$(ls *.0)

test -z "${FILES}" && exit 0

for i in ${FILES} ; do
  echo "[SED] ${i}"
  sed -e "s/!VERSION!/${1}/g" -e "s/!DATE!/`date $d '+%B %Y'`/g" < ${i} > ${i%%0}1
done
