name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  # ubuntu-20.04
  ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build ladi-jack2
      shell: bash
      run: |
        python3 ./waf configure --prefix=/usr
        python3 ./waf
        python3 ./waf install --destdir=$(pwd)/destdir
